### PR TITLE
feat(token): add token expiration refresh

### LINKED ISSUE #15: Refresh access token if its about to expire
For every request access token ,refresh token are sent as cookies to the server 
- send an expiry time cookie which has unix time stamp of the expiry date, generate this when access token is generated 
- for every future request in the base handler, check the current time stamp and the expiry time stamp
- if it is about to expire in about lets say 5 min, send the request to refresh endpoint 
- get the refresh token from the cookie and talk to spotify via their api and save the access, refresh token and expiry unix time stamp 
- finally send the request to base url

### PR DESCRIPTION
**Pull request by v0lp3**
I think this is the right way to do token expiration, no need to set  timestamp in cookie. Is timestamp important for other reasons?

close #15

### CODE REVIEW

**Comment by itslychee** [comment]
Don't think it closes #15, but this PR does makes things more coherent. As a matter of fact, I'm almost close to being done with resolving #15 myself

**Comment by v0lp3** [comment]
What do you mean? What miss to close #15 in your opinion?
UNIX timestamp is redundant to implement this.

**Comment by itslychee** [comment]
> What do you mean? What miss to close #15 in your opinion?

It is not actually refreshing the token when it is expired

>  UNIX timestamp is redundant for this.

I never referred to UNIX timestamps, what are you getting at?

**Comment by v0lp3** [comment]
It refresh the token when it is expired lol

> I never referred to UNIX timestamps, what are you getting at?

I refer to issue.

**Comment by itslychee** [comment]
> 
> 
> It refresh the token when it is expired lol

Could you point me to where it does? I could be genuinely missing something, because GitHub's change comparisons are telling me otherwise

**Comment by v0lp3** [comment]
> > It refresh the token when it is expired lol
> 
> Could you point me to where it does? I could be genuinely missing something, because GitHub's change comparisons are telling me otherwise

There isn't new code for this. When token expires It reuse the code already implemented to grab the token the first time.

**Comment by itslychee** [comment]
> There isn't new code for this because it reuse the code already implemented to grab the token the first time when token expires.

But why do this when you could utilize the `refresh_token` field? Check the 4th row [here](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow) to see what I'm talking about.

**Comment by v0lp3** [comment]
> > There isn't new code for this because it reuse the code already implemented to grab the token the first time when token expires.
> 
> But why do this when you could utilize the `refresh_token` field? Check the 4th row [here](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow) to see what I'm talking about.

You are right, but `refresh_token` is out of scope **in this moment**, because the page is served statically. Anyway my pull request is more a fix than a feature.

**Comment by kmarrip** [comment]
@v0lp3 unix time stamp is not redundant here, the access token that is sent back after authentication is not a jwt token, as far i can seen thats some cryptographic string. 
i understand you made the cookies life time to equal to 3600, but the point is  what would happen when it expires it simply won't be sent. i need to be able to tell if the cookie is going to expire in the next 5 min for i can refresh it.

**Comment by itslychee** [comment]
> You are right, but `refresh_token` is out of scope **in this moment**, because the page is served statically. Anyway my pull request is more a fix than a feature.

The page also has cookies set with the names of `RefreshToken` and `Token`. They are not out of scope

**Pull request closed without merging**
