### PR TITLE
Add test cases issue #10

### PR DESCRIPTION
**Pull request by stanipetrosyan**
Hello, I created tests for all packages. Some points:

- I created Spotify interface so is easy testing its method. This interface I think should be better that it contains GetTokenFromSpotify method (Because it is a method that has to do with the interface), but I leave you to make decision, its your project :) 
- For testing spotify interface I used Mock object and I created directory for future mocks. This is a best practice in unit testing
- For testing calls to spotify api like in spotify package I created my own server with httptest.NewServer()
- I changed some usage of gin and I divided handlers in two file. I think is better have one file for one handler

That's all. I hope everything goes well :)

### CODE REVIEW

**Comment by kmarrip** [comment]
Great work @StaniPetrosyan 
Will check and close this issue by weekend, thanks for ur effort

**Comment by kmarrip** [comment]
hey @StaniPetrosyan i know this is too much to ask but  the point is i have merged another pr and because of that some conflicts have come up in this one. can you check resolve them please 
thanks

**Comment by stanipetrosyan** [comment]
Yes, no problem :)

**Comment by stanipetrosyan** [comment]
Hi, I solved conflicts. I noticed that the callback and main API now has new logic. Probably missing a couple of tests on a couple of series, but at least now it's almost all tested.
I think that from here on it is necessary that each new feature also includes the addition / modification of tests to have everything consistent.

**Comment by kmarrip** [comment]
Hey @StaniPetrosyan thanks for the amazing work. Yes, new features need to have rest cases included. Will check the pr and merge by weekend.

**Pull request merged**
